zerobyte_timezone: "America/Chicago"
zerobyte_base_url: "http://localhost:4096"
zerobyte_image: "ghcr.io/nicotsx/zerobyte:v0.35"
zerobyte_deploy_dir: "/home/lennon/docker/zerobyte"
zerobyte_backup_home: "/home/lennon"
zerobyte_backup_etc: "/etc"
